@url = http://localhost:3000
@producerId = 3

### Listar todos os produtores
GET {{url}}/producers
Content-Type: application/json

### Criar um produtor
POST {{url}}/producers
Content-Type: application/json

{
  "name": "Julian Campos",
  "type": "Pessoa Fisica",
  "documentType": "CPFF",
  "documentNumber": "711.408.470-66"
}

#### Criar um produtor e uma fazenda
POST {{url}}/producers
Content-Type: application/json

{
  "name": "Julian",
  "documentType": "CPF",
  "documentNumber": "938.811.280-69",
  "farm": {
    "name": "Fazend 2",
    "city": "Igarape",
    "state": "Minas Gerais",
    "totalArea": "53",
    "productiveArea": "33",
    "vegetationArea": "20",
    "cultivation": ["feijão"]
  }
}

##### Atualizar um produtor
PUT {{url}}/producer/{{producerId}}
Content-Type: application/json

{
  "name": "Julian Oliveira Campos"
}

##### Excluir um produtor
DELETE {{url}}/producer/{{producerId}}
Content-Type: application/json
