-- AlterTable
ALTER TABLE "Farm" ALTER COLUMN "totalArea" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "productableArea" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "vegetableArea" SET DATA TYPE DOUBLE PRECISION;
